name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to access full git history for file timestamps

      - name: Generate images.json from scans/
        run: |
          rm -f images.json
          find scans -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) | while read -r file; do
            timestamp=$(git log -1 --format="%cI" -- "$file" || date -Iseconds)
            echo "{\"src\": \"$file\", \"created\": \"$timestamp\"}," >> tmp_images.json
          done
          echo "[" > images.json
          sed '$ s/,$//' tmp_images.json >> images.json
          echo "]" >> images.json
          rm tmp_images.json

      - name: Commit and push images.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add images.json
          git commit -m "Auto-update images.json from scans/" || echo "No changes to commit"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
